name: Update Datasets

on: 
  workflow_dispatch:
  schedule:
    - cron: '30 5 * * TUE'

run-name: Updating Datasets

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest release
        uses: rez0n/actions-github-release@main
        id: latest_release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ncbi/datasets
          type: "stable"
          
      - uses: actions/checkout@v3
     
      - name: Remove V
        id: strip
        run: |
          version=$(echo "${{ steps.latest_release.outputs.release }}" | sed 's/V//g' | sed 's/v//g' )
          echo "The version is $version"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: pull repo
        uses: actions/checkout@v3
        
      - name: check paths
        run: ls && ls ./datasets
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Quay
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build and push to Quay
        uses: docker/build-push-action@v3
        with:
          file: ./datasets/Dockerfile
          build-args: DATASETS_VER=${{ steps.strip.outputs.version }}
          push: true
          tags: quay.io/uphl/datasets:${{ steps.strip.outputs.version }}

      - name: Build and push latest tag to Quay
        uses: docker/build-push-action@v3
        with:
          file: ./datasets/Dockerfile
          build-args: DATASETS_VER=${{ steps.strip.outputs.version }}
          push: true
          tags: quay.io/uphl/datasets:latest   
